/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FieldType {
  Text = Text,
  TextArea = TextArea,
  ComboBox = ComboBox,
  MultipleChoice = MultipleChoice,
  CheckBox = CheckBox,
  DateTime = DateTime,
  Number = Number
}
