/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ComponentDto } from '../models/component-dto';
export interface PageDto {
  components?: Array<ComponentDto> | null;
  description?: string | null;
  icon?: string | null;
  id?: number;
  label?: string | null;
  name?: string | null;
}
