/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  createdAt?: string;
  email?: string | null;
  fullName?: string | null;
  id?: number;
  passwordHash?: string | null;
  username?: string | null;
}
