/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuElementDto } from '../models/menu-element-dto';
export interface ApplicationDto {
  description?: string | null;
  icon?: string | null;
  id?: number;
  label?: string | null;
  menuElements?: Array<MenuElementDto> | null;
  name?: string | null;
  version?: string | null;
}
