/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ComponentType } from '../models/component-type';
import { DatabaseTableDto } from '../models/database-table-dto';
import { FormComponentFieldDto } from '../models/form-component-field-dto';
export interface ComponentDto {
  description?: string | null;
  fields?: Array<FormComponentFieldDto> | null;
  hasPagination?: boolean | null;
  icon?: string | null;
  id?: number;
  isVisible?: boolean;
  label?: string | null;
  name?: string | null;
  order?: number;
  table?: DatabaseTableDto;
  tableId?: number;
  type?: ComponentType;
}
