/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DatabaseColumnDto } from '../models/database-column-dto';
export interface DatabaseTableDto {
  columns?: Array<DatabaseColumnDto> | null;
  description?: string | null;
  id?: number;
  label?: string | null;
  name?: string | null;
}
