/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DatabaseColumnDto {
  dataType?: string | null;
  description?: string | null;
  id?: number;
  isIndexed?: boolean;
  isNullable?: boolean;
  isPrimaryKey?: boolean;
  label?: string | null;
  name?: string | null;
  tableId?: number;
}
