/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FieldType {
  Text = 0,
  TextArea = 1,
  ComboBox = 2,
  MultipleChoice = 3,
  CheckBox = 4,
  DateTime = 5,
  Number = 6
}
