/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationDto } from '../../models/application-dto';

export interface ApiApplicationDetailsIdGet$Plain$Params {
  id: number;
}

export function apiApplicationDetailsIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiApplicationDetailsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationDto>> {
  const rb = new RequestBuilder(rootUrl, apiApplicationDetailsIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationDto>;
    })
  );
}

apiApplicationDetailsIdGet$Plain.PATH = '/api/Application/Details/{id}';
