/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ComponentDto } from '../models/component-dto';
import { DatabaseColumnDto } from '../models/database-column-dto';
import { FieldType } from '../models/field-type';
export interface FormComponentFieldDto {
  column?: DatabaseColumnDto;
  columnId?: number;
  component?: ComponentDto;
  componentId?: number;
  description?: string | null;
  displayColumn?: DatabaseColumnDto;
  displayColumnId?: number | null;
  id?: number;
  label?: string | null;
  length?: number | null;
  name?: string | null;
  order?: number;
  regex?: string | null;
  type?: FieldType;
  value?: string | null;
}
