/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageDto } from '../models/page-dto';
export interface MenuElementDto {
  description?: string | null;
  icon?: string | null;
  id?: number;
  isVisible?: boolean;
  label?: string | null;
  name?: string | null;
  order?: number;
  page?: PageDto;
  pageId?: number | null;
  parentId?: number | null;
}
